### PR TITLE
Quicker pgkyl install directions using Mamba

### PR DESCRIPTION
**Pull request by sfrnk**
Added directions to install pgkl using Mamba. This effectively fixes the slow install issue that was present before.

### CODE REVIEW

**Comment by pcagas** [comment]
Does it work without `conda update -n base -c defaults conda`? On several systems, if conda is not updated, it fails to pull the latest version of `adios2`. And without the latest version of `adios2` dynVectors like integrated energy don't work properly.

**Comment by sfrnk** [comment]
> Does it work without `conda update -n base -c defaults conda`? On several systems, if conda is not updated, it fails to pull the latest version of `adios2`. And without the latest version of `adios2` dynVectors like integrated energy don't work properly.

Good question. It looks like it does not install 2.9.2; it installs 2.9.1. This is a NERSC problem as you simply cannot run that update command there due to the way they have configured user permissions with conda and may be something that is worth working out with the consultants. Mana says that his postgykl works fine on NERSC on 2.9.1?

**Comment by pcagas** [comment]
If it runs properly than great! :-)

**Comment by sfrnk** [comment]
I double checked with my install postgkyl runs fine.

**Pull request merged**
